# Generated by Django 5.2.8 on 2025-11-15 16:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("schools", "0002_add_trigram_index"),
    ]

    operations = [
        migrations.CreateModel(
            name="UniformSpec",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("academic_year", models.CharField(help_text="e.g. 2025-2026", max_length=20)),
                ("description", models.TextField()),
                ("item_type", models.CharField(max_length=100)),
                ("item_name", models.CharField(max_length=100)),
                ("gender", models.CharField(max_length=20)),
                ("season", models.CharField(max_length=50)),
                ("fabric_gsm", models.IntegerField()),
                ("pantone", models.CharField(max_length=50)),
                ("measurements", models.JSONField(default=dict)),
                ("frozen", models.BooleanField(default=False)),
                ("version", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uniform_specs",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "db_table": "uniform_specs",
                "ordering": ["item_type", "-version"],
                "indexes": [
                    models.Index(
                        fields=["school", "item_type", "version"],
                        name="idx_school_item_version",
                    )
                ],
            },
        ),
    ]
