# Generated by Django 5.2.8 on 2025-11-16 07:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                "CREATE INDEX IF NOT EXISTS idx_spec_school_item ON uniform_specs (school_id, item_type);",
                "CREATE INDEX IF NOT EXISTS idx_spec_gender ON uniform_specs (gender);",
            ],
            reverse_sql=[
                "DROP INDEX IF EXISTS idx_spec_school_item;",
                "DROP INDEX IF EXISTS idx_spec_gender;",
            ],
        ),
    ]
