# Generated by Django 5.2.8 on 2025-11-15 16:32

from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, connection


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0001_initial"),
    ]

    operations = []

    # Only add trigram index for PostgreSQL
    if connection.vendor == "postgresql":
        operations = [
            TrigramExtension(),
            migrations.RunSQL(
                sql="CREATE INDEX idx_school_name_trgm ON schools USING gin (name gin_trgm_ops);",
                reverse_sql="DROP INDEX IF EXISTS idx_school_name_trgm;",
            ),
        ]
