# Generated by Django 5.2.8 on 2025-11-16 07:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vendors", "0001_initial"),
    ]

    operations = [
        # Note: Price cap validation is enforced at application level in serializers
        # SQLite doesn't support complex CHECK constraints with subqueries
        # For PostgreSQL, this would be:
        # migrations.RunSQL(
        #     sql="""
        #     ALTER TABLE listings ADD CONSTRAINT check_price_cap
        #     CHECK (
        #         mrp <= base_price * (1 + (
        #             SELECT max_markup_pct / 100
        #             FROM price_policies
        #             WHERE school_id = listings.school_id
        #         ))
        #     );
        #     """,
        #     reverse_sql="ALTER TABLE listings DROP CONSTRAINT check_price_cap;"
        # ),
    ]
