# Generated by Django 5.2.8 on 2025-11-16 07:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vendors", "0002_add_price_cap_constraint"),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                "CREATE INDEX IF NOT EXISTS idx_listing_vendor_enabled ON listings (vendor_id, enabled);",
                "CREATE INDEX IF NOT EXISTS idx_listing_school_item ON listings (school_id, spec_id);",
                "CREATE INDEX IF NOT EXISTS idx_approval_status ON vendor_approvals (status, expires_at);",
            ],
            reverse_sql=[
                "DROP INDEX IF EXISTS idx_listing_vendor_enabled;",
                "DROP INDEX IF EXISTS idx_listing_school_item;",
                "DROP INDEX IF EXISTS idx_approval_status;",
            ],
        ),
    ]
