# Generated by Django 5.2.8 on 2025-11-21 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vendors", "0003_add_performance_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="email",
            field=models.EmailField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="vendor",
            name="gst_number",
            field=models.CharField(
                blank=True, db_index=True, max_length=15, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="official_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="vendor",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=15),
        ),
        migrations.AddField(
            model_name="vendor",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="vendor_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddIndex(
            model_name="vendor",
            index=models.Index(fields=["status"], name="idx_vendor_status"),
        ),
        migrations.AddIndex(
            model_name="vendor",
            index=models.Index(fields=["gst_number"], name="idx_vendor_gst"),
        ),
    ]
